[package]
name = "statico"
version = "0.6.2"
edition = "2021"
authors = ["Nicola Bonelli <nicola@larthia.com>"]
description = "A blazing-fast HTTP server implemented in Rust that serves static responses at lightning speed."
license = "MIT OR Apache-2.0"
repository = "https://github.com/awgn/statico"
readme = "README.md"
keywords = ["cli", "utility", "benchmark", "http"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
hyper = { version = "1.8", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1.49", features = ["full"] }
http-body-util = "0.1"
bytes = "1.11"
socket2 = { version = "0.6", features = ["all"] }
anyhow = "1.0"
num_cpus = "1.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
httparse = "1.10.1"
http_wire = "0.5.0"
smol = { version = "2.0", optional = true }
smol-hyper = { version = "0.1", optional = true }
http-body = "1.0.1"
pingora-timeout = "0.6.0"
humantime = "2.3.0"
owo-colors = "4.2.3"
contatori = "0.7.5"
ctrlc = "3.5.1"
dashmap = "6.1"
pin-project-lite = "0.2.16"
futures-lite = "1.13.0"
core_affinity = "0.8.3"
futures = "0.3.31"
tokio-stream = { version = "0.1.18", features = ["net"] }
number_range = "0.3.2"

[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = { version = "0.5.0", optional = true }
monoio = { version = "0.2", optional = true }
io-uring = { version = "0.6", optional = true }
glommio = { version = "0.8.0", optional = true }

[features]
tokio_uring = ["dep:tokio-uring"]
monoio = ["dep:monoio", "dep:io-uring"]
glommio = ["dep:glommio"]
smol = ["dep:smol", "dep:smol-hyper"]
full = ["tokio_uring", "monoio", "glommio", "smol"]

[profile.release]
debug = false
opt-level = 3
strip = true
codegen-units = 1
lto = true
